name: Trigger Sematext Synthetics Checks

on:
  deployment_status

permissions:
  contents: read   # Allows access to repository content
  statuses: write  # Allows updating commit statuses
  checks: write    # Allows creating and updating check runs

jobs:
  sematext_synthetics_check:
    runs-on: ubuntu-latest
    steps:
      - name: Run Sematext Synthetics CI/CD Integration
        uses: your-org/sematext-synthetics-action@v1
        with:
          monitor_group_id: 1   # Replace with your actual Monitor Group ID
          region: EU            # Replace with your Sematext Cloud Region ('EU' or 'US')
        env:
          SEMATEXT_API_KEY: ${{ secrets.SEMATEXT_API_KEY }}
